### PR TITLE
Added exceptional handling for smooth exit

### PR DESCRIPTION
**Pull request by mekaustubh28**
I have added smooth exiting in the command i.e. try, except.
when you type `exit` code exits smoothly but when you press `crtl+c` or `^C` which is a very common method to end code via terminal then the code exits forcefully which is not a good practice.

You can check the images I have attached.

Screenshot from 2021-10-03 23-47-44
Screenshot from 2021-10-03 23-47-25

### CODE REVIEW

**Review by Ccode-lang — CHANGES_REQUESTED** [review]
You should change "Thanks for coding" to something like "Exiting."

**Review by Ccode-lang — COMMENTED** [review]
Commit does not fix anything on my side.
```
>>^CTraceback (most recent call last):
  File "lang.py", line 6, in <module>
    inp = input(">>").lstrip()
KeyboardInterrupt
```
EDIT:
I was using wrong branch sorry.

**Comment by mekaustubh28** [comment]
Send the ss of code

**Comment by Ccode-lang** [comment]
I put edit on the comment from before.
> EDIT:
> I was using wrong branch sorry.

Didn't know you were getting these through email.

**Comment by Ccode-lang** [comment]
I can fix after merge.

**Review by Ccode-lang — APPROVED** [review]

**Comment by mekaustubh28** [comment]
No problem...

**Pull request merged**
